services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    MLukman\DoctrineHelperBundle\Service\:
        resource: '../src/Service/'

    MLukman\DoctrineHelperBundle\EventSubscriber\AuditedEntitySubscriber:
        calls:
            - setSecurity: ['@?Symfony\Bundle\SecurityBundle\Security']

    MLukman\DoctrineHelperBundle\DataCollector\RequestBodyConverterCollector:
        tags:
            - name: data_collector
              id: 'doctrine_helper.request_body_conversions'
